### ISSUE TITLE
게시글 UI 제작

### ISSUE THREAD

**Issue by ddyokim** [Lambmukja/snap_market#23]
게시글 업로드 후 보이는 페이지

**Comment by ddyokim** [comment]
추천 평점: 코멘트 형태로 제작

**Comment by ddyokim** [comment]
![-](https://user-images.githubusercontent.com/10115416/49385165-19687f80-f760-11e8-9f09-936230462230.png)

**Comment by jmg7173** [comment]
TODO: 태그정보, 마켓 정보
필요 API: 촬영 신청하기

Model에 필드 추가: 사진 저장할 수 있는  필드

**Comment by jmg7173** [comment]
#14 를 하면서 같이 만들어놓음.

**Comment by ddyokim** [comment]
TODO:
![image](https://user-images.githubusercontent.com/10115416/50233752-6fdbec00-03f7-11e9-95c2-49580f1d9f3c.png)
**빈 값 표시되게 해야함!**
