### ISSUE TITLE
포트폴리오 게시글 등록 페이지 관련 정보

### ISSUE THREAD

**Issue by picseo** [Lambmukja/snap_market#29]
[포트폴리오 게시글이라는 설명 text]
[지역 입력창] [요일 입력창] [시간 입력창] [금액 입력창]
[사진 업로드 버튼]
[올린 사진들 뷰]

--------------------------------------------------------
포트폴리오 게시글 페이지 구성 요소
- [x] 포트폴리오 게시글 text
- [x] 지역 입력창
- [ ] 요일 입력창
- [ ] 시간 입력창
- [x] 금액 입력창
- [x] 사진 업로드 버튼
- [ ] 올린 사진들 뷰(?)

-------------------------------------------------------------
생성되는 포트폴리오 값
-지역
-날짜
-시간 
-금액
-작가 ID
-게시글 번호(한 작가가 여러개 올릴시 구분이 필요하기 위해서)???

**Comment by jmg7173** [comment]
#22

**Comment by jmg7173** [comment]
요일 추가?
